/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as DatatypesRouteImport } from './routes/datatypes'
import { Route as ConstructsRouteImport } from './routes/constructs'
import { Route as ChampionRouteImport } from './routes/champion'
import { Route as IndexRouteImport } from './routes/index'

const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const DatatypesRoute = DatatypesRouteImport.update({
  id: '/datatypes',
  path: '/datatypes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructsRoute = ConstructsRouteImport.update({
  id: '/constructs',
  path: '/constructs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionRoute = ChampionRouteImport.update({
  id: '/champion',
  path: '/champion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/constructs': typeof ConstructsRoute
  '/datatypes': typeof DatatypesRoute
  '/keywords': typeof KeywordsRoute
  '/operators': typeof OperatorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/constructs': typeof ConstructsRoute
  '/datatypes': typeof DatatypesRoute
  '/keywords': typeof KeywordsRoute
  '/operators': typeof OperatorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champion': typeof ChampionRoute
  '/constructs': typeof ConstructsRoute
  '/datatypes': typeof DatatypesRoute
  '/keywords': typeof KeywordsRoute
  '/operators': typeof OperatorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champion'
    | '/constructs'
    | '/datatypes'
    | '/keywords'
    | '/operators'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champion'
    | '/constructs'
    | '/datatypes'
    | '/keywords'
    | '/operators'
  id:
    | '__root__'
    | '/'
    | '/champion'
    | '/constructs'
    | '/datatypes'
    | '/keywords'
    | '/operators'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionRoute: typeof ChampionRoute
  ConstructsRoute: typeof ConstructsRoute
  DatatypesRoute: typeof DatatypesRoute
  KeywordsRoute: typeof KeywordsRoute
  OperatorsRoute: typeof OperatorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datatypes': {
      id: '/datatypes'
      path: '/datatypes'
      fullPath: '/datatypes'
      preLoaderRoute: typeof DatatypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructs': {
      id: '/constructs'
      path: '/constructs'
      fullPath: '/constructs'
      preLoaderRoute: typeof ConstructsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champion': {
      id: '/champion'
      path: '/champion'
      fullPath: '/champion'
      preLoaderRoute: typeof ChampionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionRoute: ChampionRoute,
  ConstructsRoute: ConstructsRoute,
  DatatypesRoute: DatatypesRoute,
  KeywordsRoute: KeywordsRoute,
  OperatorsRoute: OperatorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
