/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitconverterRouteImport } from './routes/unitconverter'
import { Route as MultiplechoiceRouteImport } from './routes/multiplechoice'
import { Route as FilesizeRouteImport } from './routes/filesize'
import { Route as CapacitycalculatorRouteImport } from './routes/capacitycalculator'
import { Route as IndexRouteImport } from './routes/index'

const UnitconverterRoute = UnitconverterRouteImport.update({
  id: '/unitconverter',
  path: '/unitconverter',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplechoiceRoute = MultiplechoiceRouteImport.update({
  id: '/multiplechoice',
  path: '/multiplechoice',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesizeRoute = FilesizeRouteImport.update({
  id: '/filesize',
  path: '/filesize',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitycalculatorRoute = CapacitycalculatorRouteImport.update({
  id: '/capacitycalculator',
  path: '/capacitycalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacitycalculator': typeof CapacitycalculatorRoute
  '/filesize': typeof FilesizeRoute
  '/multiplechoice': typeof MultiplechoiceRoute
  '/unitconverter': typeof UnitconverterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacitycalculator': typeof CapacitycalculatorRoute
  '/filesize': typeof FilesizeRoute
  '/multiplechoice': typeof MultiplechoiceRoute
  '/unitconverter': typeof UnitconverterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacitycalculator': typeof CapacitycalculatorRoute
  '/filesize': typeof FilesizeRoute
  '/multiplechoice': typeof MultiplechoiceRoute
  '/unitconverter': typeof UnitconverterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capacitycalculator'
    | '/filesize'
    | '/multiplechoice'
    | '/unitconverter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capacitycalculator'
    | '/filesize'
    | '/multiplechoice'
    | '/unitconverter'
  id:
    | '__root__'
    | '/'
    | '/capacitycalculator'
    | '/filesize'
    | '/multiplechoice'
    | '/unitconverter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacitycalculatorRoute: typeof CapacitycalculatorRoute
  FilesizeRoute: typeof FilesizeRoute
  MultiplechoiceRoute: typeof MultiplechoiceRoute
  UnitconverterRoute: typeof UnitconverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unitconverter': {
      id: '/unitconverter'
      path: '/unitconverter'
      fullPath: '/unitconverter'
      preLoaderRoute: typeof UnitconverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplechoice': {
      id: '/multiplechoice'
      path: '/multiplechoice'
      fullPath: '/multiplechoice'
      preLoaderRoute: typeof MultiplechoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filesize': {
      id: '/filesize'
      path: '/filesize'
      fullPath: '/filesize'
      preLoaderRoute: typeof FilesizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitycalculator': {
      id: '/capacitycalculator'
      path: '/capacitycalculator'
      fullPath: '/capacitycalculator'
      preLoaderRoute: typeof CapacitycalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacitycalculatorRoute: CapacitycalculatorRoute,
  FilesizeRoute: FilesizeRoute,
  MultiplechoiceRoute: MultiplechoiceRoute,
  UnitconverterRoute: UnitconverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
